### ISSUE TITLE
CONFIG: fixa code signing för mac 

### ISSUE THREAD

**Issue by oolars** [kits-ab/LogLady#206]

**Comment by Doverstav** [comment]
Verkar inte riktigt funka på Mac. Behöver nog notariseras. Se länk: https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/

**Comment by Eightquake** [comment]
Nej, det stämmer. Jag håller på och kollar på hur det ska göras samt på hur man gör det i samband med build i Travis :)

**Comment by Doverstav** [comment]
Okej, vad bra! Jag var nog lite ivrig, trodde det var färdigt och drog iväg den till done, men jag var nog inte så insatt som jag trodde...

Men bra att du har koll på läget, då är det ingen ko på isen :)
