### ISSUE TITLE
CONFIG: Ta bort oanvända dependencies från package.json

### ISSUE THREAD

**Issue by Eightquake** [kits-ab/LogLady#392]
CONFIG: Remove unused dependencies from package.json

Currently, there are a few unused packages in the project. We should evaluate what package should be removed and which should stay. By running `npm depcheck` you get a list of unused packages.

**Comment by Glazastik** [comment]
Visar sig att några dependencies används i scripten, devdep hittar inte dem

**Comment by Eightquake** [comment]
Yes, några av de som depcheck säger behövs fortfarande. concurrently, wait-on och cross-env vet jag på rak arm används endast i npm scripts.

Men det finns andra paket som kanske inte används alls, t.ex Material UI och react-window. Och vissa som skulle kunna vara dev-dependency istället, t.ex. wait-on.

Depcheck kan vara en grund för att sen kolla igenom listan och bestämma själv för varje paket :)
