### ISSUE TITLE
REDUCERS: Rensa settingsState- och topPanelState-settings objekten när vi stänger filer. (se bild i kommentar)

### ISSUE THREAD

**Issue by MelindaSW** [kits-ab/LogLady#475]

**Comment by MelindaSW** [comment]
Här är endast två filer öppna men statet har kvar infon om de två filer som tidigare stängts. 

![image](https://user-images.githubusercontent.com/45069965/75166005-87151880-5723-11ea-9571-630826b27b72.png)

**Comment by Doverstav** [comment]
Ja, bra att du upptäckte det! När en fil stängs kallas `clearSource()` i `dispatchActions.js`, där tas det bort en del info om loggen men vi har glömt att ta bort all den nya datan vi lagt till. Den funktionen är nog en bra startpunkt för att lösa det här!
