### ISSUE TITLE
BUG: Tomma rader är högre än fyllda rader

### ISSUE THREAD

**Issue by gustavjorlov** [kits-ab/LogLady#485]
<img width="259" alt="Screenshot 2020-03-05 at 11 45 03" src="https://user-images.githubusercontent.com/12250187/75974445-10241080-5ed7-11ea-81f3-050d32c04849.png">

**Comment by Atmanea** [comment]
Lägger till notering att de rader som är tomma försvinner när man scrollar bort och sedan tillbaka, vilket gör att det inte blir varannan mörk och varannan ljus rad just där de försvann.
