### ISSUE TITLE
Assess impact of acorn security vulnerability and make a recommendation

### ISSUE THREAD

**Issue by psandboge** [kits-ab/LogLady#498]
Should we fix and make a new release immediately, or can it wait until our next ordinary release?

Issue #493 Bump acorn from 5.7.3 to 5.7.4

**Comment by MelindaSW** [comment]
I ran the tests and started loglady on my machine and things seem to work as they should. I checked the prescence of acorn in the source code, as far as I can see its only occurance is in package-lock.json. We are not using the package anywhere. I am new to these security bug checks so let me know if I can look at something else.

**Comment by psandboge** [comment]
You only need to read what the new version fixes. If you think Loglady users would be at risk without the fix, then we need to update as soon as possible. However, I think that is unlikely, since Loglady is a local application. But it's your call.

**Comment by MelindaSW** [comment]
I can not find anything in the changelog nor in the commits that triggers any warning bells. The only change seems to be an addition to regexp validators, and we are not using the package in our code. From my perspective it seems like we can wait until the next release.
