### ISSUE TITLE
Bugg/engine-cache returnerar inte alltid rätt innehåll

### ISSUE THREAD

**Issue by MelindaSW** [kits-ab/LogLady#522]
I filer på tex 25mb gör Innehållet ibland ett skutt och de sista raderna blir dubletter. Gör så att engine och backend cachen hanterar detta bättre.

**Comment by gustavjorlov** [comment]
Går det att konstruera ett test som påvisar buggen?

**Comment by MelindaSW** [comment]
Garanterat:) Har en misstanke om vad det kan vara för fel så ska se om det går att reproducera med tester.
